#include "Company.h"
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlQueryModel>
#include <QDebug>

Company::Company() {}

bool Company::createCompany(const QString &name,
                            const QString &location,
                            const QString &email,
                            const QString &phone,
                            const QString &preferredFish,
                            const QString &status)
{
    QSqlDatabase db = QSqlDatabase::database(); // uses default connection

    if (!db.isOpen()) {
        qDebug() << "Database is not open!";
        return false;
    }

    QSqlQuery query(db);

    // Use named placeholders
    // Note: COMPANY_ID will be auto-generated by a sequence (you may need to create one)
    query.prepare("INSERT INTO COMPANIES (NAME, LOCATION, EMAIL, PHONE, PREFERRED_FISH, STATUS) "
                  "VALUES (:name, :location, :email, :phone, :preferredFish, :status)");

    // Bind values by name
    query.bindValue(":name", name);
    query.bindValue(":location", location.isEmpty() ? QVariant(QVariant::String) : location);
    query.bindValue(":email", email.isEmpty() ? QVariant(QVariant::String) : email);
    query.bindValue(":phone", phone.isEmpty() ? QVariant(QVariant::String) : phone);
    query.bindValue(":preferredFish", preferredFish);
    query.bindValue(":status", status);

    if (!query.exec()) {
        qDebug() << "Error inserting company:" << query.lastError().text();
        qDebug() << "Query attempted:" << query.lastQuery();
        qDebug() << "Bound values - Name:" << name << "Status:" << status;
        return false;
    }

    qDebug() << "Company created successfully!";
    return true;
}

// Read - Get all companies
QSqlQueryModel* Company::getAllCompanies()
{
    QSqlQueryModel *model = new QSqlQueryModel();
    model->setQuery("SELECT COMPANY_ID, NAME, EMAIL, PHONE, PREFERRED_FISH, LOCATION, STATUS "
                    "FROM COMPANIES ORDER BY COMPANY_ID DESC");

    if (model->lastError().isValid()) {
        qDebug() << "Error loading companies:" << model->lastError().text();
    }

    // Set friendly column headers
    model->setHeaderData(0, Qt::Horizontal, "ID");
    model->setHeaderData(1, Qt::Horizontal, "Name");
    model->setHeaderData(2, Qt::Horizontal, "Email");
    model->setHeaderData(3, Qt::Horizontal, "Phone");
    model->setHeaderData(4, Qt::Horizontal, "Preferred Fish");
    model->setHeaderData(5, Qt::Horizontal, "Location");
    model->setHeaderData(6, Qt::Horizontal, "Status");

    return model;
}

// Read - Search companies
QSqlQueryModel* Company::searchCompanies(const QString &searchText)
{
    QSqlQueryModel *model = new QSqlQueryModel();

    QSqlQuery query;
    query.prepare("SELECT COMPANY_ID, NAME, EMAIL, PHONE, PREFERRED_FISH, LOCATION, STATUS "
                  "FROM COMPANIES "
                  "WHERE UPPER(NAME) LIKE :search OR UPPER(PHONE) LIKE :search "
                  "OR UPPER(EMAIL) LIKE :search OR UPPER(LOCATION) LIKE :search "
                  "ORDER BY COMPANY_ID DESC");

    QString searchPattern = "%" + searchText.toUpper() + "%";
    query.bindValue(":search", searchPattern);

    if (!query.exec()) {
        qDebug() << "Error searching companies:" << query.lastError().text();
    }

    model->setQuery(query);

    // Set friendly column headers
    model->setHeaderData(0, Qt::Horizontal, "ID");
    model->setHeaderData(1, Qt::Horizontal, "Name");
    model->setHeaderData(2, Qt::Horizontal, "Email");
    model->setHeaderData(3, Qt::Horizontal, "Phone");
    model->setHeaderData(4, Qt::Horizontal, "Preferred Fish");
    model->setHeaderData(5, Qt::Horizontal, "Location");
    model->setHeaderData(6, Qt::Horizontal, "Status");

    return model;
}

// Update company
bool Company::updateCompany(int companyId,
                            const QString &name,
                            const QString &location,
                            const QString &email,
                            const QString &phone,
                            const QString &preferredFish,
                            const QString &status)
{
    QSqlDatabase db = QSqlDatabase::database();

    if (!db.isOpen()) {
        qDebug() << "Database is not open!";
        return false;
    }

    QSqlQuery query(db);
    query.prepare("UPDATE COMPANIES SET "
                  "NAME = :name, "
                  "LOCATION = :location, "
                  "EMAIL = :email, "
                  "PHONE = :phone, "
                  "PREFERRED_FISH = :preferredFish, "
                  "STATUS = :status "
                  "WHERE COMPANY_ID = :id");

    query.bindValue(":name", name);
    query.bindValue(":location", location);
    query.bindValue(":email", email);
    query.bindValue(":phone", phone);
    query.bindValue(":preferredFish", preferredFish);
    query.bindValue(":status", status);
    query.bindValue(":id", companyId);

    if (!query.exec()) {
        qDebug() << "Error updating company:" << query.lastError().text();
        return false;
    }

    qDebug() << "Company updated successfully!";
    return true;
}

// Delete company
bool Company::deleteCompany(int companyId)
{
    QSqlDatabase db = QSqlDatabase::database();

    if (!db.isOpen()) {
        qDebug() << "Database is not open!";
        return false;
    }

    QSqlQuery query(db);
    query.prepare("DELETE FROM COMPANIES WHERE COMPANY_ID = :id");
    query.bindValue(":id", companyId);

    if (!query.exec()) {
        qDebug() << "Error deleting company:" << query.lastError().text();
        return false;
    }

    qDebug() << "Company deleted successfully!";
    return true;
}

// Get company by ID
QSqlQuery Company::getCompanyById(int companyId)
{
    QSqlQuery query;
    query.prepare("SELECT COMPANY_ID, NAME, LOCATION, EMAIL, PHONE, PREFERRED_FISH, STATUS "
                  "FROM COMPANIES WHERE COMPANY_ID = :id");
    query.bindValue(":id", companyId);
    query.exec();

    return query;
}

QString Company::getLastError()
{
    QSqlDatabase db = QSqlDatabase::database();
    return db.lastError().text();
}
